### ISSUE TITLE
Port configuration / testing against a local datastore?

### ISSUE THREAD

**Issue by MercifulCode** [HumanCellAtlas/dcp-cli#145]
Hello! I'm trying to use the DCP CLI against a locally running server that implements the HCA's datastore swagger API.

I have a local server up and can access `http://localhost:8888/api/swagger.json` to see my local copy of the swagger spec (with the staging host replaced with localhost).

Following the readme, I created this config.json for the CLI:

```json
{"DSSClient": {"swagger_url": "http://localhost:8888/api/swagger.json"}, "log_level": "INFO", "client_id": "foo"}
```

However, when I try to run the cli I get this error:

```sh
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /internal/application_secrets (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10bc28050>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

It seems that the port I specified is being ignored - Is this behavior expected? Is there a way to use the cli to interact with a local server?

Thanks!

**Comment by calvinnhieu** [comment]
Hey @MercifulCode,

I believe this is an SSL issue, but to be sure can you post the full stack trace?

**Comment by MercifulCode** [comment]
Sure!

```sh
Traceback (most recent call last):
  File "/usr/local/bin/hca", line 13, in <module>
    cli.main()
  File "/usr/local/lib/python2.7/site-packages/hca/cli.py", line 73, in main
    result = parsed_args.entry_point(parsed_args)
  File "/usr/local/lib/python2.7/site-packages/hca/util/__init__.py", line 152,in _cli_call
    return self._consume_response(self._request(vars(cli_args)))
  File "/usr/local/lib/python2.7/site-packages/hca/util/__init__.py", line 127,in _request
    session = self.client.get_authenticated_session()
  File "/usr/local/lib/python2.7/site-packages/hca/util/__init__.py", line 336,in get_authenticated_session
    oauth2_client_data = self.application_secrets["installed"]
  File "/usr/local/lib/python2.7/site-packages/hca/util/__init__.py", line 264,in application_secrets
    self.config.application_secrets = requests.get(app_secrets_url).json()
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 512,in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 622,in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 513,in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /internal/application_secrets (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1063f3290>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

**Comment by calvinnhieu** [comment]
Hey @MercifulCode, how are you running your local server? I noticed your local server isn't serving from `/v1/swagger.json` - [this](https://github.com/HumanCellAtlas/data-store#running-the-dss-api-locally) may be related.

The CLI enforces SSL on API connections, explaining port 443. Unfortunately, this is hardcoded in the CLI source and in order to connect the CLI to a local DSS API server, you'll need to modify and use a local version of the [CLI](https://github.com/HumanCellAtlas/dcp-cli):

In `dcp-cli/hca/util/__init__.py`, modify the value of `scheme` on line 175 to `http`. This should resolve the port 443 error. Follow the [docs](https://github.com/HumanCellAtlas/dcp-cli#development) to set up and build the CLI locally. Let me know if you run into any issues!

**Comment by MercifulCode** [comment]
I am running a local server by using a stubbed out nodejs server created by https://swagger.io/tools/swagger-codegen/ .

Thanks for the pointer to the scheme line in __init__.py! Looks like it is still throwing some errors, and I've tried a few combinations, like setting my node server to use port 443 (with sudo to start it).

```sh
 hca dss get-subscriptions --replica aws
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /internal/application_secrets (Caused by SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:1045)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/hca", line 13, in <module>
    cli.main()
  File "/usr/local/lib/python3.7/site-packages/hca/cli.py", line 73, in main
    result = parsed_args.entry_point(parsed_args)
  File "/usr/local/lib/python3.7/site-packages/hca/util/__init__.py", line 152, in _cli_call
    return self._consume_response(self._request(vars(cli_args)))
  File "/usr/local/lib/python3.7/site-packages/hca/util/__init__.py", line 127, in _request
    session = self.client.get_authenticated_session()
  File "/usr/local/lib/python3.7/site-packages/hca/util/__init__.py", line 336, in get_authenticated_session
    oauth2_client_data = self.application_secrets["installed"]
  File "/usr/local/lib/python3.7/site-packages/hca/util/__init__.py", line 264, in application_secrets
    self.config.application_secrets = requests.get(app_secrets_url).json()
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /internal/application_secrets (Caused by SSLError(SSLError(1, '[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:1045)')))
```

My understanding is that the `swagger_url` key needs to point to any accessible `swagger.json`. Regarding the dss-api, I have been unable to run the local server from the datastore repo for a few days now. For posterity, that error is:

```sh
./dss-api
Traceback (most recent call last):
  File "./dss-api", line 12, in <module>
    from chalice.cli import CLIFactory, run_local_server
ImportError: No module named chalice.cli
```

**Comment by calvinnhieu** [comment]
Hm not sure exactly what's causing your issue, but there are a couple potential environment issues:

- `data-store` requires Python 3.6 (not 3.7) to run since AWS Lambda currently only supports Python 3.6. Sorry for the confusion! I'll update the docs to be clearer about this.
- re: `dss-api`, have you run `pip install -r requirements-dev.txt`? Were you able to run it in the past?

I suspect downgrading to Python 3.6 should resolve some of your issues.

**Comment by MercifulCode** [comment]
Ah, I didn't realize that regarding python 3.6 - thanks!

That did resolve the chalice error, thankfully - Now I'm getting some invalid security token errors - I only have aws configured, do I need to also setup accounts for google/azure? Sorry for all the sudden questions!

```sh
./dss-api
WARNING:root:It appears that logging was already configured in this interpreter process. Currently registered handlers, formatters and filters will be left as is.
Stack (most recent call last):
  File "./dss-api", line 38, in <module>
    chalice_stage_name=os.environ["DSS_DEPLOYMENT_STAGE"]
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/chalice/cli/factory.py", line 108, in create_config_obj
    app_obj = self.load_chalice_app()
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/chalice/cli/factory.py", line 166, in load_chalice_app
    app = importlib.import_module('app')
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "./chalice/app.py", line 36, in <module>
    configure_lambda_logging()
  File "/Users/andrewd/Workspace/GitHub/MercifulCode/data-store/dss/logging.py", line 56, in configure_lambda_logging
    _configure_logging(stream=sys.stdout)
  File "/Users/andrewd/Workspace/GitHub/MercifulCode/data-store/dss/logging.py", line 87, in _configure_logging
    stack_info=True)
ERROR:connexion.apis.abstract:Failed to add operation for HEAD /v1/files/{uuid}
Traceback (most recent call last):
  File "./dss-api", line 38, in <module>
    chalice_stage_name=os.environ["DSS_DEPLOYMENT_STAGE"]
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/chalice/cli/factory.py", line 108, in create_config_obj
    app_obj = self.load_chalice_app()
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/chalice/cli/factory.py", line 166, in load_chalice_app
    app = importlib.import_module('app')
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "./chalice/app.py", line 269, in <module>
    dss_app = create_app()
  File "/Users/andrewd/Workspace/GitHub/MercifulCode/data-store/dss/__init__.py", line 197, in create_app
    app.add_api('../dss-api.yml', resolver=resolver, validate_responses=True, arguments=os.environ)
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/connexion/apps/flask_app.py", line 54, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/connexion/apps/abstract.py", line 159, in add_api
    options=api_options.as_dict())
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/connexion/apis/abstract.py", line 131, in __init__
    self.add_paths()
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/connexion/apis/abstract.py", line 252, in add_paths
    self._handle_add_operation_error(path, method, sys.exc_info())
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/connexion/apis/abstract.py", line 263, in _handle_add_operation_error
    six.reraise(*exc_info)
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/connexion/apis/abstract.py", line 242, in add_paths
    self.add_operation(method, path, endpoint, path_parameters)
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/connexion/apis/abstract.py", line 195, in add_operation
    pythonic_params=self.pythonic_params)
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/connexion/operation.py", line 215, in __init__
    resolution = resolver.resolve(self)
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/connexion/resolver.py", line 40, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/connexion/resolver.py", line 62, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/connexion/utils.py", line 34, in get_function_from_name
    module = importlib.import_module(module_name)
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/andrewd/Workspace/GitHub/MercifulCode/data-store/dss/api/files.py", line 13, in <module>
    from dss import DSSException, dss_handler, stepfunctions
  File "/Users/andrewd/Workspace/GitHub/MercifulCode/data-store/dss/stepfunctions/__init__.py", line 20, in <module>
    accountid = ARN.get_account_id()
  File "/Users/andrewd/Workspace/GitHub/MercifulCode/data-store/dss/util/aws/__init__.py", line 32, in get_account_id
    cls._default_account_id = clients.sts.get_caller_identity()["Account"]
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/andrewd/.pyenv/versions/3.6.0/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.
```

**Comment by calvinnhieu** [comment]
You should be able to run `./dss-api` by just configuring AWS credentials. Are your [AWS credentials](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-quick-configuration) are set up correctly?

**Comment by MercifulCode** [comment]
They are, yep - and I also figured out what was wrong!

I was sourcing `environment` instead of `environment.local` in the datastore repo.

Thank you for all the help so far! This is my current setup/progress:

I have a datastore up and running at localhost:5000 by running `./dss-api` with and with this as my environment.local:

```sh
AWS_DEFAULT_REGION=us-east-2
DSS_S3_CHECKOUT_BUCKET=chell-hca-data-store
DSS_S3_CHECKOUT_BUCKET_TEST=chell-hca-data-store-test
API_DOMAIN_NAME=localhost
```

I can confirm that `http://localhost:5000/v1/swagger.json` leads to the right file.

The `~/.config/hca/config.json` is set up as:

```json
{"log_level": "INFO", "client_id": "foo", "DSSClient": {"swagger_url": "http://localhost:5000/v1/swagger.json"}}
```

And I'm running a locally built CLI with `scheme = "https"` changed to `scheme = "http"` per above.

The CLI is now hanging when I try to run a command, like `hca dss login`, `hca dss get-subscriptions --replica aws`, or `hca upload --help`. But that definitely seems like a major step in the right direction!

**Comment by calvinnhieu** [comment]
No problem! I believe `API_DOMAIN_NAME` needs to include the port: 

`API_DOMAIN_NAME=localhost:5000`

**Comment by MercifulCode** [comment]
Noted!

```
hca dss get-subscriptions --replica aws
Traceback (most recent call last):
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x10e54bc50>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /internal/application_secrets (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10e54bc50>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrewd/.pyenv/versions/3.6.6/bin/hca", line 13, in <module>
    cli.main()
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hca/cli.py", line 73, in main
    result = parsed_args.entry_point(parsed_args)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hca/util/__init__.py", line 152, in _cli_call
    return self._consume_response(self._request(vars(cli_args)))
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hca/util/__init__.py", line 127, in _request
    session = self.client.get_authenticated_session()
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hca/util/__init__.py", line 336, in get_authenticated_session
    oauth2_client_data = self.application_secrets["installed"]
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hca/util/__init__.py", line 264, in application_secrets
    self.config.application_secrets = requests.get(app_secrets_url).json()
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=443): Max retries exceeded with url: /internal/application_secrets (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10e54bc50>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

Hmmm

**Comment by calvinnhieu** [comment]
Make sure you're using `http` wherever you're hitting localhost. Also, since you've been reconfiguring quite a bit, it might be helpful to simply wipe the config files in `~/.config/hca/` - running `hca` will regenerate them.

**Comment by MercifulCode** [comment]
Yeah, definitely - thanks!

Similar to the above, it looks like using the http scheme for the CLI will default to port 80 which is also unbindable by default. 

The local datastore, however, is using port 5000. Would you happen to know how this is reconciled in development for the DCP ?

**Comment by calvinnhieu** [comment]
All you should need to do to configure the CLI to hit your local data-store is set the correct `DSSClient.swagger_url` in `~/.config/hca/config.json`. For example:

`"DSSClient": {"swagger_url": "http://localhost:5000/v1/swagger.json"}`

**Comment by MercifulCode** [comment]
Unfortunately, it looks like the port is being ignored there too:

```sh
hca dss upload --replica aws --staging-bucket chell-hca-data-store-test --src-dir data-bundle-examples/smartseq2/paired_ends
INFO:hca:Uploading 5 files from data-bundle-examples/smartseq2/paired_ends to chell-hca-data-store-test
INFO:hca:File cell.json: registering...
INFO:hca:File cell.json: registering from s3://chell-hca-data-store-test/780f5ad8-fc6e-46da-b674-3c65becd9579/cell.json -> uuid 780f5ad8-fc6e-46da-b674-3c65becd9579
Traceback (most recent call last):
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10a2673c8>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  [Previous line repeated 6 more times]
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /v1/files/780f5ad8-fc6e-46da-b674-3c65becd9579?version=2018-07-31T213749.539697Z (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a2673c8>: Failed to establish a new connection: [Errno 61] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrewd/.pyenv/versions/3.6.6/bin/hca", line 13, in <module>
    cli.main()
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hca/cli.py", line 73, in main
    result = parsed_args.entry_point(parsed_args)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hca/util/__init__.py", line 443, in arg_forwarder
    return command(**command_args)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hca/dss/__init__.py", line 245, in upload
    source_url=source_url
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hca/util/__init__.py", line 135, in _request
    timeout=self.client.timeout_policy)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Users/andrewd/.pyenv/versions/3.6.6/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /v1/files/780f5ad8-fc6e-46da-b674-3c65becd9579?version=2018-07-31T213749.539697Z (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a2673c8>: Failed to establish a new connection: [Errno 61] Connection refused',))
```

These are my env variables:

```sh
API_DOMAIN_NAME=localhost:5000
SWAGGER_URL=http://${API_DOMAIN_NAME}/v1/swagger.json
```

When I go to `http://localhost:5000/v1/swagger.json`, the `host` key is set to `"localhost:5000"`, and my `config.json` is `"DSSClient": {"swagger_url": "http://localhost:5000/v1/swagger.json"}`

My best guess is some kind of port forwarding needs to be setup, but I'm not 100% sure.

**Comment by calvinnhieu** [comment]
The value in `config.json` should be a dict:

`{"DSSClient": {"swagger_url": "http://localhost:5000/v1/swagger.json"}}`

**Comment by calvinnhieu** [comment]
Also, have you created [these S3 buckets](https://github.com/HumanCellAtlas/data-store#aws) and set the corresponding environment variables in `environment.local`?

**Comment by MercifulCode** [comment]
Ah, sorry for the confusion, my config.json is a dict, I was just pasting the relevant key:value pair.

And my buckets should be all set!

**Comment by calvinnhieu** [comment]
Do you have another file in `~/.config/hca/` with a long filename? Can you open that up and check what the `host` field is set to?

**Comment by calvinnhieu** [comment]
Great! Closing issue as original issue was solved

**Comment by ttung** [comment]
> The CLI enforces SSL on API connections, explaining port 443. Unfortunately, this is hardcoded in the CLI source and in order to connect the CLI to a local DSS API server, you'll need to modify and use a local version of the CLI:

Can we bypass this restriction for localhost connections?

**Comment by calvinnhieu** [comment]
@ttung That makes sense
